#!/usr/bin/env bash
#
# gen-privapp-permissions.sh
#
# Generates the privapp-permissions whitelist from the microG build actually
# installed on the connected device.
#
# Why generate instead of ship a fixed list: with
# ro.control_privapp_permissions=enforce, a privileged permission missing from
# the whitelist is denied — and on userdebug builds a missing entry can stop the
# device booting. A list copied from a different microG build is exactly how that
# happens. Reading the installed build's own manifest keeps the two in step.
#
# Requires: adb, a connected device, microG installed. No Android SDK needed.

set -euo pipefail

PKG="com.google.android.gms"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/module/system/etc/permissions/privapp-permissions-${PKG}.xml"

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

command -v adb >/dev/null 2>&1 || die "adb not found in PATH"

if [ "$(adb devices | grep -c -w "device")" -eq 0 ]; then
  die "no device connected (check 'adb devices')"
fi

printf 'Querying %s on device...\n' "$PKG"

if ! adb shell pm path "$PKG" 2>/dev/null | grep -q "package:"; then
  die "$PKG is not installed. Install microG first."
fi

VERSION="$(adb shell dumpsys package "$PKG" 2>/dev/null \
  | grep -m1 "versionName=" | sed 's/.*versionName=//' | tr -d '\r')"
printf 'Found microG version: %s\n' "${VERSION:-unknown}"

# The 'requested permissions:' block lists everything the manifest declares.
# Both the /system and /data package entries may appear once the module is
# installed, so deduplicate. Only platform permissions belong in this whitelist.
PERMS="$(adb shell dumpsys package "$PKG" 2>/dev/null \
  | sed -n '/requested permissions:/,/install permissions:/p' \
  | grep -o 'android\.permission\.[A-Z_0-9]*' \
  | sort -u)"

if [ -z "$PERMS" ]; then
  die "could not read requested permissions from dumpsys (unexpected output format)"
fi

COUNT="$(printf '%s\n' "$PERMS" | wc -l | tr -d ' ')"

if [ "$COUNT" -lt 20 ]; then
  die "only $COUNT permissions found — the query looks wrong; refusing to write an unsafe whitelist"
fi

if ! printf '%s\n' "$PERMS" | grep -q "INSTALL_LOCATION_PROVIDER"; then
  die "INSTALL_LOCATION_PROVIDER not requested by this build — is this really microG?"
fi

mkdir -p "$(dirname "$OUT")"

{
  printf '<?xml version="1.0" encoding="utf-8"?>\n'
  printf '<!--\n'
  printf '  Generated by scripts/gen-privapp-permissions.sh\n'
  printf '  Source: %s as installed on the build device\n' "$PKG"
  printf '  microG version: %s\n' "${VERSION:-unknown}"
  printf '  Do not hand-edit. Regenerate if you change microG version.\n'
  printf '-->\n'
  printf '<permissions>\n'
  printf '    <privapp-permissions package="%s">\n' "$PKG"
  printf '%s\n' "$PERMS" | while IFS= read -r p; do
    [ -n "$p" ] && printf '        <permission name="%s"/>\n' "$p"
  done
  printf '    </privapp-permissions>\n'
  printf '</permissions>\n'
} > "$OUT"

printf 'wrote %s permissions to:\n  %s\n' "$COUNT" "$OUT"
printf '\nNext: ./scripts/build-module.sh\n'
